manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmkfirmware
    - name: inorichi
      url-base: https://github.com/inorichi

  projects:
    - name: zmk
      remote: zmk
      revision: 4ec69cb7e658590adf6354027aca789b364a70c5 # pinned main (2025-10-30)
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: 1d9c2c68ca76012e1b1e5f6ef02fa5eadc4ca399 # pinned (2025-10-30)
      path: modules/pmw3610

  self:
    path: config
